import "./globals.css";
import React from "react";
import AuthContext from "@/components/context/AuthContext";
import Nav from "@/components/Nav";
import { Toaster } from "@/components/ui/toaster";
import BusinessContext from "@/components/context/BusinessContext";
import ProfileContext from "@/components/context/ProfileContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactElement;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <BusinessContext>
            <ProfileContext>
              <Nav />
              {children}
            </ProfileContext>
            <Toaster />
          </BusinessContext>
        </AuthContext>
      </body>
    </html>
  );
}
